"""adicionar_campos_auditoria

Revision ID: 3d25a7dd102c
Revises: c4f560ddc523
Create Date: 2025-05-06 22:41:09.245600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d25a7dd102c'
down_revision: Union[str, None] = 'c4f560ddc523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('usuario_cadastro_id', sa.Integer(), nullable=True))
    op.add_column('empresas', sa.Column('usuario_alteracao_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'empresas', 'users', ['usuario_alteracao_id'], ['id'])
    op.create_foreign_key(None, 'empresas', 'users', ['usuario_cadastro_id'], ['id'])
    op.add_column('grupos', sa.Column('usuario_cadastro_id', sa.Integer(), nullable=True))
    op.add_column('grupos', sa.Column('usuario_alteracao_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'grupos', 'users', ['usuario_alteracao_id'], ['id'])
    op.create_foreign_key(None, 'grupos', 'users', ['usuario_cadastro_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grupos', type_='foreignkey')
    op.drop_constraint(None, 'grupos', type_='foreignkey')
    op.drop_column('grupos', 'usuario_alteracao_id')
    op.drop_column('grupos', 'usuario_cadastro_id')
    op.drop_constraint(None, 'empresas', type_='foreignkey')
    op.drop_constraint(None, 'empresas', type_='foreignkey')
    op.drop_column('empresas', 'usuario_alteracao_id')
    op.drop_column('empresas', 'usuario_cadastro_id')
    # ### end Alembic commands ###
