"""criar_tabela_atendimentos

Revision ID: ba919f358e77
Revises: 36f8d931ce07
Create Date: 2025-05-07 16:56:22.472070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba919f358e77'
down_revision: Union[str, None] = '36f8d931ce07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atendimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocolo', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('AGUARDANDO', 'EM_ANDAMENTO', 'FINALIZADO', name='statusatendimento'), nullable=True),
    sa.Column('contato_id', sa.Integer(), nullable=False),
    sa.Column('atendente_id', sa.Integer(), nullable=True),
    sa.Column('iniciado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atendido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['atendente_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contato_id'], ['contatos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atendimentos_id'), 'atendimentos', ['id'], unique=False)
    op.create_index(op.f('ix_atendimentos_protocolo'), 'atendimentos', ['protocolo'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_atendimentos_protocolo'), table_name='atendimentos')
    op.drop_index(op.f('ix_atendimentos_id'), table_name='atendimentos')
    op.drop_table('atendimentos')
    # ### end Alembic commands ###
