"""adicionar_atendimento_id_a_mensagens

Revision ID: ff7c1731b5de
Revises: ba919f358e77
Create Date: 2025-05-07 16:56:55.962304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff7c1731b5de'
down_revision: Union[str, None] = 'ba919f358e77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mensagens', sa.Column('atendimento_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'mensagens', 'atendimentos', ['atendimento_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mensagens', type_='foreignkey')
    op.drop_column('mensagens', 'atendimento_id')
    # ### end Alembic commands ###
